### ISSUE TITLE
Missing dependancy during install

### ISSUE THREAD

**Issue by foddergreenwood** [DeepWoods/nxfilter-pfsense#1]
First, most grateful for the effort put forth by the author. I am using PF sense 2.3.5-RELEASE (i386)
FreeBSD 10.3-RELEASE-p22. When running the script, when it gets to the line Installing dejavu-2.37...,the next line reports pkg; missing dependancy 'mkfontdir' followed by an error where it reports Failed to install the following package .....dejavu-2.37.txz. Then it goes on, and a few lines later it reports installing openjdk8 followed by error pkg:Missing dependancy 'dejavu'. Then reports unable to install openjdk8...
Any direction available for a FreeBSD newbie?

**Comment by DeepWoods** [comment]
Thanks for the feedback.  If you're up for editing the install script yourself, try changing the line "AddPkg mkfontscale" to "AddPkg mkfontdir" at around line 132.  I've not tested the script on anything prior to 2.4 which is FreeBSD 11 based.  If that doesn't fix the dependency error, I'll spin up a VM of a 2.3.5 install and see if I can fix the issue.

**Comment by foddergreenwood** [comment]
I did find the line that needs editing, however, I don't know how to edit script, then get edited one to run from command, instead of original. Thanks for looking. I can set up a standalone dns, it just looked like such a great idea, I was going to try it. Thanks again.
