### ISSUE TITLE
NXFilter does not run on PFsense 2.5xxx

### ISSUE THREAD

**Issue by marciointerface** [DeepWoods/nxfilter-pfsense#4]
#sockstat -4 -l 

port 53 UDP => xinetd

**Comment by marciointerface** [comment]
In these versions 2.5.1 and 2.5.2 to nxfilter run, need before, check if xinetd uses port 53, and yes, stop service.

**Comment by DeepWoods** [comment]
Latest updated script tested and working  with v2.5 and v2.6 of pfSense.  Disabling the default DNS resolver is required to prevent a port conflict.
