### ISSUE TITLE
nxfilter fails to install on fresh install of pfSense 2.6

### ISSUE THREAD

**Issue by mithubindia** [DeepWoods/nxfilter-pfsense#5]
Have tried your script on fresh install of pfSense 2.6 community edition.  [ Hardware corei3 / 8 gb / 240 GB SSD ]
On investigation, found that the script pulls openjdk but fails to install. [ failed dependency for package  dejavu  ]

**Comment by DeepWoods** [comment]
This should be taken care of with the lastest update.
